### ISSUE TITLE
Docker image for armv7

### ISSUE THREAD

**Issue by svillar** [ronhks/panasonic-aquarea-smart-cloud-mqtt#1]
It'd awesome if you could provide an official image for armv7 devices as well. There are tons of rpi3 willing to run the software :smile:

**Comment by ronhks** [comment]
done :)
https://hub.docker.com/layers/panasonic-aquarea-smart-cloud-mqtt/ronhks/panasonic-aquarea-smart-cloud-mqtt/1.1.1-armv7/images/sha256-e38327155dd99177fdb28b64ce9fa6392540712ade7948afe497bc5f31d10aa1?context=explore

**Comment by svillar** [comment]
> done :) https://hub.docker.com/layers/panasonic-aquarea-smart-cloud-mqtt/ronhks/panasonic-aquarea-smart-cloud-mqtt/1.1.1-armv7/images/sha256-e38327155dd99177fdb28b64ce9fa6392540712ade7948afe497bc5f31d10aa1?context=explore

Working great! Many thanks!

**Comment by ronhks** [comment]
> > done :) https://hub.docker.com/layers/panasonic-aquarea-smart-cloud-mqtt/ronhks/panasonic-aquarea-smart-cloud-mqtt/1.1.1-armv7/images/sha256-e38327155dd99177fdb28b64ce9fa6392540712ade7948afe497bc5f31d10aa1?context=explore
> 
> Working great! Many thanks!

Great! I'm so happy! :) If you experience any bug welcome to report them :)
