### ISSUE TITLE
Energy Conspumption API Error

### ISSUE THREAD

**Issue by Revo7** [ronhks/panasonic-aquarea-smart-cloud-mqtt#6]
Hello, i have problem with connection.:

 Empty response from Energy Conspumption API
ERRO[0017] Error while get DeviceData
![image](https://user-images.githubusercontent.com/32430822/183900788-68f72f49-c6db-47ea-a165-3e1f888e2174.png)

I think all my config are ok, the same as login through the web interface

![image](https://user-images.githubusercontent.com/32430822/183901040-632f98ca-59d1-4725-918b-8abaf7a0d628.png)

**Comment by ronhks** [comment]
Hi!

Can you try please with the version 1.1.2?
It has the same behavior?

**Comment by Revo7** [comment]
Hi ! I use git clone https://github.com/ronhks/panasonic-aquarea-smart-cloud-mqtt 
to download, it clone the las releases version. Where i can find or how to install the 1.1.2 version ?

**Comment by ronhks** [comment]
ohh, I though, you use docker. The docker versions available on hub: 
https://hub.docker.com/repository/docker/ronhks/panasonic-aquarea-smart-cloud-mqtt

I forget to create 1.1.2 and 1.1.3 versions in github. I will fix it.

**Comment by Revo7** [comment]
no, i use linux amd64 version, i use it on proxmox (linux)

**Comment by Revo7** [comment]
Please give me some note when you update release

**Comment by svillar** [comment]
I think this was previously reported [here](https://github.com/ronhks/panasonic-aquarea-smart-cloud-mqtt/issues/5#issuecomment-1209611722)

**Comment by ronhks** [comment]
> I think this was previously reported [here](https://github.com/ronhks/panasonic-aquarea-smart-cloud-mqtt/issues/5#issuecomment-1209611722)

Yes, So I link the issues.

**Comment by ronhks** [comment]
> Please give me some note when you update release

Actually I'm at a huge load, but I would like to create an update at the weekend. 🙏

**Comment by ronhks** [comment]
I fixed the problem. Sorry for inconveniences and thanks for your patience!

The new version available on dockerhub:
https://hub.docker.com/repository/registry-1.docker.io/ronhks/panasonic-aquarea-smart-cloud-mqtt/general
