### ISSUE TITLE
Docker compose .yml

### ISSUE THREAD

**Issue by rybber78** [ronhks/panasonic-aquarea-smart-cloud-mqtt#7]
Hi

Great project! Can you make a Docker Compose .yml file pls?

**Comment by ronhks** [comment]
I will do it in a week.

**Comment by rybber78** [comment]
Did it myself:

  panasonic-aquarea:
    image: ronhks/panasonic-aquarea-smart-cloud-mqtt
    container_name: panasonic-aquarea
    restart: unless-stopped
    volumes:
      - CONFIG_LOCATION:/app/etc

**Comment by ronhks** [comment]
Sorry for late reply, but my daughter born at december, so i had a few time :)
Thanks, I will put on the repository!
