### ISSUE TITLE
Heating operations and set temperature on two zones

### ISSUE THREAD

**Issue by elcoda** [ronhks/panasonic-aquarea-smart-cloud-mqtt#9]
Dears,
I'm using your tool on my Raspberry and it's phenomenal.

I don't know GoLang... but am I right if I say that the tool now is able to manage heating only for one zone?
I my case I have two zones and I see that when I turn on heating via mqtt only one of those (the first) will be really turned on and there is no way to change the heating temp.

Am I right?

In that case I can try add some methods on heat.go to create also a way to change temperature and use two zones.

Many thanks

P.S.
This can be useful to interate Aquarea with PV systems and use heating when PV production is higher.

**Comment by ronhks** [comment]
I thick so did it and I merged the changes.
So I close the issue.
